import { API_BASE_URL } from './config';
import { ApiError, NetworkError } from './errors';
import { renewAccessToken } from './session-bridge';

/**
 * The server's envelope. Doc 04 §1, D-011.
 *
 * <p>Every response has this shape, including errors, so there is exactly one
 * place that unwraps it — a screen never sees `{ data, error, meta }`.
 */
interface Envelope<T> {
  data: T | null;
  error: { code: string; message: string; details?: Record<string, unknown> } | null;
  meta?: Record<string, unknown>;
}

export interface RequestOptions {
  method?: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  body?: unknown;
  /** Sent as `Idempotency-Key`. Mandatory on the operations doc 04 §21 lists. */
  idempotencyKey?: string;
  token?: string | null;
  /** Abort signal, so a screen that unmounts stops waiting. */
  signal?: AbortSignal;
  /** Overrides the default retry policy for this call. */
  retries?: number;
}

/** Correlates a request across the app's logs and the server's (doc 09 §15). */
function newRequestId(): string {
  return `mp-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * A client-generated idempotency key. Doc 04 §21.
 *
 * <p>Generated by the **caller** and reused across retries of the same user
 * action — that is the whole mechanism. A key generated inside the retry loop
 * would be a new key each attempt, which is the same as having none: a retried
 * checkout would place a second order.
 */
export function newIdempotencyKey(): string {
  const random = () => Math.random().toString(16).slice(2, 10);
  return `${Date.now().toString(16)}-${random()}-${random()}`;
}

const DEFAULT_RETRIES = 2;
const MAX_BACKOFF_MS = 8000;

async function wait(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Call the API.
 *
 * <p>Handles the three things every call needs and no screen should repeat:
 * unwrapping the envelope, turning an error body into a typed {@link ApiError},
 * and backing off when the server throttles.
 *
 * <p><b>A 429 is honoured, not guessed at.</b> The server sends `Retry-After`
 * (D-050) and this waits exactly that long. Retrying immediately is what turns a
 * throttle into an outage — and the OTP endpoint is the one a user is most likely
 * to hammer.
 *
 * <p><b>Only idempotent or idempotency-keyed calls are retried.</b> A GET is safe
 * to repeat; a POST is only safe when it carries a key the server can
 * deduplicate. Retrying an unkeyed POST is how one tap becomes two orders.
 */
export async function apiRequest<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const method = options.method ?? 'GET';
  const retryable = method === 'GET' || options.idempotencyKey != null;
  const maxAttempts = (options.retries ?? (retryable ? DEFAULT_RETRIES : 0)) + 1;

  // An expired access token is not a failed request, it is a stale credential.
  // Renewing once and repeating the call is safe for any method: the server
  // never saw the original, having rejected it at authentication.
  let token = options.token;
  let renewed = false;

  let lastError: unknown;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await performRequest<T>(path, method, { ...options, token });
    } catch (error) {
      lastError = error;

      if (error instanceof ApiError && error.isUnauthenticated && token != null && !renewed) {
        renewed = true;
        const fresh = await renewAccessToken();
        if (fresh != null) {
          token = fresh;
          // Does not count as an attempt: nothing was wrong with the request.
          attempt -= 1;
          continue;
        }
        // No renewal available or the session is genuinely over. Report the 401
        // so the app signs out rather than retrying into a wall.
        break;
      }

      const isLast = attempt === maxAttempts;
      if (isLast) break;

      if (error instanceof ApiError) {
        if (!error.isRetryable) break;
        // The server told us how long. Guessing shorter makes it worse.
        const waitMs = error.retryAfterSeconds != null
          ? error.retryAfterSeconds * 1000
          : Math.min(MAX_BACKOFF_MS, 2 ** attempt * 250);
        await wait(waitMs);
        continue;
      }

      if (error instanceof NetworkError) {
        await wait(Math.min(MAX_BACKOFF_MS, 2 ** attempt * 250));
        continue;
      }

      break;
    }
  }

  throw lastError;
}

async function performRequest<T>(
  path: string,
  method: string,
  options: RequestOptions,
): Promise<T> {
  const headers: Record<string, string> = {
    Accept: 'application/json',
    'X-Request-Id': newRequestId(),
  };
  if (options.body !== undefined) headers['Content-Type'] = 'application/json';
  if (options.token) headers.Authorization = `Bearer ${options.token}`;
  if (options.idempotencyKey) headers['Idempotency-Key'] = options.idempotencyKey;

  let response: Response;
  try {
    response = await fetch(`${API_BASE_URL}${path}`, {
      method,
      headers,
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
      signal: options.signal,
    });
  } catch (error) {
    // An aborted request is the screen going away, not a failure to report.
    if ((error as Error)?.name === 'AbortError') throw error;
    throw new NetworkError();
  }

  // 204 and friends: nothing to unwrap.
  if (response.status === 204) return undefined as T;

  let envelope: Envelope<T> | null = null;
  const text = await response.text();
  if (text) {
    try {
      envelope = JSON.parse(text) as Envelope<T>;
    } catch {
      envelope = null;
    }
  }

  if (!response.ok) {
    const retryAfter = response.headers.get('Retry-After');
    throw new ApiError({
      code: envelope?.error?.code ?? 'UNEXPECTED_ERROR',
      // The server's message is written for the person reading it. Replacing it
      // with our own would turn "that code has expired" into "something failed".
      message: envelope?.error?.message ?? 'Something went wrong. Please try again.',
      status: response.status,
      requestId: envelope?.meta?.requestId as string | undefined,
      details: envelope?.error?.details,
      retryAfterSeconds: retryAfter ? Number(retryAfter) : undefined,
    });
  }

  return (envelope?.data ?? (undefined as T)) as T;
}

/** A page of a cursor-paginated collection. Doc 04 §20. */
export interface Page<T> {
  items: T[];
  nextCursor?: string;
  hasMore: boolean;
}
