import { apiRequest, newIdempotencyKey } from '@/lib/api/client';
import type {
  Alternatives,
  PaymentMethod,
  Procurement,
  Requirement,
  SubmitResponse,
  SupplierOrder,
} from '@/models/procurement';

// ── Cart ──────────────────────────────────────────────────────────────

/** The outlet's open cart. Returns an empty procurement when there is none. */
export function fetchCart(token: string, outletId: number): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/outlets/${outletId}/cart`, { token });
}

export function addCartItem(
  token: string,
  outletId: number,
  body: { supplierOfferId: number; quantity: string; requirementItemId?: number },
): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/outlets/${outletId}/cart/items`, {
    method: 'POST',
    token,
    body,
  });
}

export function updateCartItem(
  token: string,
  itemId: number,
  quantity: string,
): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurement-items/${itemId}`, {
    method: 'PATCH',
    token,
    body: { quantity },
  });
}

export function removeCartItem(token: string, itemId: number): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurement-items/${itemId}`, {
    method: 'DELETE',
    token,
  });
}

export function setPaymentMethod(
  token: string,
  procurementId: number,
  paymentMethod: PaymentMethod,
): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}/payment-method`, {
    method: 'PATCH',
    token,
    body: { paymentMethod },
  });
}

export function fetchProcurement(token: string, procurementId: number): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}`, { token });
}

/**
 * Re-price against live offers.
 *
 * <p>`acceptPriceChanges` is the restaurant's explicit answer to a change the
 * previous validation surfaced (§23A.16, guardrail 13). Passing `true`
 * speculatively would accept a price the user was never shown, which is the
 * exact failure the two-step exists to prevent — so callers pass `true` only
 * from a confirmation the user actually saw.
 */
export function validateProcurement(
  token: string,
  procurementId: number,
  acceptPriceChanges: boolean,
): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}/validate`, {
    method: 'POST',
    token,
    body: { acceptPriceChanges },
  });
}

/**
 * Place the order.
 *
 * <p><b>The idempotency key is generated by the caller and reused across
 * retries</b> (doc 04 §21). A key made inside the retry loop is the same as no
 * key: a retried submit places a second order. The screen holds one key for the
 * life of one checkout attempt.
 */
export function submitProcurement(
  token: string,
  procurementId: number,
  idempotencyKey: string,
): Promise<SubmitResponse> {
  return apiRequest<SubmitResponse>(`/api/v1/procurements/${procurementId}/submit`, {
    method: 'POST',
    token,
    idempotencyKey,
  });
}

export { newIdempotencyKey };

export function approveProcurement(token: string, procurementId: number): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}/approve`, {
    method: 'POST',
    token,
  });
}

export function rejectProcurement(
  token: string,
  procurementId: number,
  reason: string,
): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}/reject`, {
    method: 'POST',
    token,
    body: { reason },
  });
}

export function cancelProcurement(token: string, procurementId: number): Promise<Procurement> {
  return apiRequest<Procurement>(`/api/v1/procurements/${procurementId}/cancel`, {
    method: 'POST',
    token,
  });
}

// ── Requirements ──────────────────────────────────────────────────────

export function fetchRequirements(token: string, outletId: number): Promise<Requirement[]> {
  return apiRequest<Requirement[]>(`/api/v1/outlets/${outletId}/requirements`, { token });
}

export function createRequirement(
  token: string,
  outletId: number,
  body: {
    items: { canonicalProductId: number; quantity: string; unit: string; notes?: string }[];
    notes?: string;
    neededBy?: string;
    source?: 'MANUAL' | 'RECOMMENDED';
  },
): Promise<Requirement> {
  return apiRequest<Requirement>(`/api/v1/outlets/${outletId}/requirements`, {
    method: 'POST',
    token,
    body,
  });
}

// ── Orders ────────────────────────────────────────────────────────────

/**
 * Who could still supply what is missing. Doc 15's recovery path.
 *
 * <p>A POST because it ranks: the server prices and scores every candidate
 * against each item's remaining quantity. It changes nothing — the restaurant
 * chooses, and choosing is a separate act.
 */
export function findSuppliersForRequirement(
  token: string,
  requirementId: number,
): Promise<Alternatives> {
  return apiRequest<Alternatives>(`/api/v1/requirements/${requirementId}/find-suppliers`, {
    method: 'POST',
    token,
  });
}

export function fetchOutletOrders(token: string, outletId: number): Promise<SupplierOrder[]> {
  return apiRequest<SupplierOrder[]>(`/api/v1/outlets/${outletId}/supplier-orders`, { token });
}

export function fetchSupplierOrder(token: string, orderId: number): Promise<SupplierOrder> {
  return apiRequest<SupplierOrder>(`/api/v1/supplier-orders/${orderId}`, { token });
}
