import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { useSession } from '@/contexts/SessionProvider';
import { useOutlet } from '@/contexts/OutletProvider';
import { useInvalidateCart } from '@/hooks/useCart';
import {
  fetchProcurement,
  newIdempotencyKey,
  setPaymentMethod,
  submitProcurement,
  validateProcurement,
} from '@/services/procurement';
import type { PaymentMethod } from '@/models/procurement';
import { PriceChangeNotice } from '@/components/procurement/PriceChangeNotice';
import { TotalsPanel } from '@/components/procurement/TotalsPanel';
import {
  MandiButton,
  MandiCard,
  MandiErrorState,
  MandiHeader,
  MandiScreen,
  MandiSkeletonList,
  MandiStickyBar,
  MandiText,
  useToast,
} from '@/components/common';
import { ApiError } from '@/lib/api/errors';
import { formatMoney, formatQuantity } from '@/utils/money';
import { submitKey } from '@/lib/queryKeys';
import { track } from '@/analytics';
import { Colors, Radius, Spacing } from '@/theme';

const SCREEN = 'REST-CHECKOUT-01';

/**
 * REST-CHECKOUT-01. Doc 05 §12.
 *
 * <p>Shows outlet, supplier, items, totals, payment method and what happens next.
 *
 * <p><b>One idempotency key per checkout attempt.</b> Doc 04 §21: the key is
 * generated by the caller and reused across retries. Generated inside the retry
 * loop it would be a fresh key each attempt — the same as having none, and a
 * retried submit would place a second order. It is held in state here for the
 * life of the screen and only replaced when a submit genuinely fails in a way
 * that means no order was created.
 *
 * <p><b>No order is successful until the backend says so</b> (doc 05 §12). The
 * screen navigates to payment on the submit response, never on optimism.
 */
export default function CheckoutScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const procurementId = Number(id);
  const router = useRouter();
  const toast = useToast();
  const { accessToken } = useSession();
  const { outlet, outletId } = useOutlet();
  const invalidateCart = useInvalidateCart();
  const queryClient = useQueryClient();

  const [idempotencyKey] = useState(() => newIdempotencyKey());

  const procurement = useQuery({
    queryKey: ['procurement', procurementId],
    queryFn: () => fetchProcurement(accessToken as string, procurementId),
    enabled: Number.isFinite(procurementId) && accessToken != null,
  });

  const data = procurement.data ?? null;

  const validate = useMutation({
    mutationFn: (acceptPriceChanges: boolean) =>
      validateProcurement(accessToken as string, procurementId, acceptPriceChanges),
    onSuccess: () => void procurement.refetch(),
    onError: (caught) =>
      toast.show(caught instanceof ApiError ? caught.message : 'Could not re-check prices.', 'error'),
  });

  const choosePayment = useMutation({
    mutationFn: (method: PaymentMethod) =>
      setPaymentMethod(accessToken as string, procurementId, method),
    onSuccess: () => void procurement.refetch(),
    onError: (caught) =>
      toast.show(caught instanceof ApiError ? caught.message : 'Could not set that.', 'error'),
  });

  const submit = useMutation({
    mutationFn: () => submitProcurement(accessToken as string, procurementId, idempotencyKey),
    onSuccess: (response) => {
      void invalidateCart();
      // The payment screen pays these. Handing them over through the cache keeps
      // them out of the URL, where a payment id has no business being.
      queryClient.setQueryData(submitKey(response.procurementId), response);
      track('order_submitted', {
        screen: SCREEN,
        outletId,
        entityId: response.procurementId,
      }, { orders: response.supplierOrders.length });

      if (response.paymentIntents.length > 0) {
        router.replace(`/(restaurant)/payment/${response.procurementId}`);
      } else {
        // Credit orders fund without a payment step.
        router.replace('/(restaurant)/(tabs)/orders');
      }
    },
    onError: (caught) => {
      if (caught instanceof ApiError && caught.isBusinessRefusal) {
        // The server refused for a reason it can state — a price moved, a limit
        // was hit. Re-read rather than guess, so the screen shows the refusal.
        void procurement.refetch();
      }
      toast.show(
        caught instanceof ApiError ? caught.message : 'Could not place the order.',
        'error',
      );
    },
  });

  const blockers = data?.blockers ?? [];
  const needsApproval = data?.approvalStatus === 'PENDING';
  const canSubmit = Boolean(data?.submittable) && !needsApproval;

  const cta = useMemo(() => {
    if (needsApproval) return 'Send for approval';
    if (data?.paymentMethod === 'CREDIT') return 'Place order on credit';
    return 'Place order and pay';
  }, [needsApproval, data?.paymentMethod]);

  return (
    <MandiScreen
      header={<MandiHeader title="Checkout" back />}
      footer={
        data == null ? undefined : (
          <MandiStickyBar>
            <View style={styles.barRow}>
              <MandiText variant="caption" color={Colors.textSecondary}>Total payable</MandiText>
              <MandiText variant="priceLarge">{formatMoney(data.totalAmount)}</MandiText>
            </View>
            <MandiButton
              label={cta}
              size="lg"
              disabled={!canSubmit}
              loading={submit.isPending}
              onPress={() => submit.mutate()}
            />
            {!canSubmit && blockers.length === 0 && !needsApproval && (
              <MandiText variant="caption" color={Colors.textTertiary} center>
                Re-check prices to continue.
              </MandiText>
            )}
          </MandiStickyBar>
        )
      }
    >
      {procurement.isPending ? (
        <MandiSkeletonList count={3} />
      ) : procurement.error || data == null ? (
        <MandiErrorState
          message="Couldn't load this order."
          onRetry={() => procurement.refetch()}
        />
      ) : (
        <>
          <MandiCard>
            <MandiText variant="caption" color={Colors.textSecondary}>Delivering to</MandiText>
            <MandiText variant="bodyEmphasis">{outlet?.name ?? 'This outlet'}</MandiText>
            {outlet && (
              <MandiText variant="caption" color={Colors.textSecondary}>
                {[outlet.addressLine1, outlet.city, outlet.pincode].filter(Boolean).join(', ')}
              </MandiText>
            )}
          </MandiCard>

          <PriceChangeNotice
            changes={data.priceChanges}
            accepting={validate.isPending}
            onAccept={() => validate.mutate(true)}
          />

          {data.validationStale && data.priceChanges.length === 0 && (
            <MandiCard>
              <MandiText variant="bodyEmphasis">Prices need a re-check</MandiText>
              <MandiText variant="caption" color={Colors.textSecondary}>
                It has been a while since these were confirmed with suppliers.
              </MandiText>
              <MandiButton
                label="Re-check prices"
                size="md"
                variant="secondary"
                loading={validate.isPending}
                onPress={() => validate.mutate(false)}
              />
            </MandiCard>
          )}

          {blockers.length > 0 && (
            <View style={styles.blockers}>
              {blockers.map((blocker, index) => (
                <View key={`${blocker.code}-${index}`} style={styles.blocker}>
                  <Ionicons name="alert-circle-outline" size={18} color={Colors.danger} />
                  <MandiText variant="caption" color={Colors.danger} style={styles.blockerText}>
                    {blocker.message}
                  </MandiText>
                </View>
              ))}
            </View>
          )}

          {needsApproval && (
            <MandiCard accentColor={Colors.warning}>
              <MandiText variant="bodyEmphasis">This order needs approval</MandiText>
              <MandiText variant="caption" color={Colors.textSecondary}>
                {data.approvalReason ?? 'Your restaurant requires approval for orders this size.'}
              </MandiText>
              {data.approverRoles.length > 0 && (
                <MandiText variant="caption" color={Colors.textTertiary}>
                  Approvers: {data.approverRoles.join(', ').replace(/_/g, ' ').toLowerCase()}
                </MandiText>
              )}
            </MandiCard>
          )}

          <PaymentMethodPicker
            selected={data.paymentMethod}
            onSelect={(method) => choosePayment.mutate(method)}
            busy={choosePayment.isPending}
          />

          {data.supplierGroups.map((group) => (
            <MandiCard key={group.supplierStoreId}>
              <View style={styles.supplierRow}>
                <MandiText variant="bodyEmphasis" style={styles.flex}>{group.supplierName}</MandiText>
                <MandiText variant="priceSmall">{formatMoney(group.total, true)}</MandiText>
              </View>
              {group.responseSlaSeconds != null && (
                <MandiText variant="caption" color={Colors.textTertiary}>
                  Has {Math.round(group.responseSlaSeconds / 60)} min to accept once you order
                </MandiText>
              )}
              {group.items.map((item) => (
                <View key={item.id} style={styles.line}>
                  <MandiText variant="caption" color={Colors.textSecondary} style={styles.flex}>
                    {item.productName} × {formatQuantity(item.quantity)} {item.unit}
                  </MandiText>
                  <MandiText variant="caption">{formatMoney(item.lineTotal)}</MandiText>
                </View>
              ))}
            </MandiCard>
          ))}

          <TotalsPanel procurement={data} />
        </>
      )}
    </MandiScreen>
  );
}

function PaymentMethodPicker({
  selected,
  onSelect,
  busy,
}: {
  selected: PaymentMethod | null;
  onSelect: (method: PaymentMethod) => void;
  busy: boolean;
}) {
  const options: { key: PaymentMethod; label: string; hint: string; icon: 'card-outline' | 'time-outline' }[] = [
    { key: 'PREPAID', label: 'Pay now', hint: 'Card, UPI or netbanking', icon: 'card-outline' },
    { key: 'CREDIT', label: 'On credit', hint: 'Against your approved limit', icon: 'time-outline' },
  ];

  return (
    <View style={styles.section}>
      <MandiText variant="bodyEmphasis">How are you paying?</MandiText>
      <View style={styles.methods}>
        {options.map((option) => {
          const active = selected === option.key;
          return (
            <Pressable
              key={option.key}
              onPress={() => onSelect(option.key)}
              disabled={busy}
              accessibilityRole="radio"
              accessibilityState={{ selected: active }}
              accessibilityLabel={`${option.label}. ${option.hint}`}
              style={[styles.method, active && styles.methodActive]}
            >
              <Ionicons
                name={option.icon}
                size={20}
                color={active ? Colors.primary : Colors.textSecondary}
              />
              <MandiText variant="captionEmphasis">{option.label}</MandiText>
              <MandiText variant="caption" color={Colors.textTertiary}>{option.hint}</MandiText>
              {/* Not colour alone — §36. */}
              {active && (
                <View style={styles.selectedRow}>
                  <Ionicons name="checkmark-circle" size={14} color={Colors.primary} />
                  <MandiText variant="caption" color={Colors.primary}>Selected</MandiText>
                </View>
              )}
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  section: { gap: Spacing.sm },
  supplierRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  line: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm, marginTop: Spacing.xs },
  barRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  blockers: { gap: Spacing.sm },
  blocker: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  blockerText: { flex: 1 },
  methods: { flexDirection: 'row', gap: Spacing.sm },
  method: {
    flex: 1,
    gap: Spacing.xs,
    padding: Spacing.cardPadding,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  methodActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  selectedRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
});
